# Generated by Django 3.2 on 2021-04-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myobj', '0002_alter_object_store_upload_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object_store',
            old_name='upload_time',
            new_name='uploadtime',
        ),
    ]
