# Generated by Django 3.2 on 2021-04-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myobj', '0003_rename_upload_time_object_store_uploadtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object_store',
            name='uploadtime',
            field=models.DateTimeField(null=True),
        ),
    ]
